language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5

before_install:
  - sudo apt-get install build-essential cmake git libboost-all-dev cmake libgmp3-dev libssl-dev libprocps3-dev pkg-config gnuplot-x11 python-markdown
  # Install GTest
  - sudo apt-get install libgtest-dev
  - sudo cmake /usr/src/gtest/CMakeLists.txt
  - sudo make -C /usr/src/gtest/
  - sudo cp /usr/src/gtest/*.a /usr/lib
  # Checking versions
  - g++ --version

# TODO (howardwu): Update this install process once libff and libfqfft support are resolved.
install:
  # Install libff
  - git clone https://github.com/scipr-lab/libff.git
  - cd libff
  - git submodule init && git submodule update
  - mkdir build && cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
  # Install libfqfft
  - git clone https://github.com/scipr-lab/libfqfft.git
  - cd libfqfft
  - mkdir build && cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..

before_script:
  # Install git submodules
  - git submodule init && git submodule update
  - mkdir build
  - cd build
  - cmake .. -DDEBUG=ON # TODO (howardwu): Run production mode in addition to debug mode

script:
  - make
  # TODO (howardwu): Resolve runtime on targets:
  # gadgetlib1_fooram_test, zk_proof_systems_r1cs_sp_ppzkpcd_test, zk_proof_systems_ram_zksnark_test
  - make check

notifications:
  email: false
